### PR TITLE
Add Science comp Greece 2015

### PR DESCRIPTION
**Pull request by geraki**

### CODE REVIEW

**Comment by JeanFred** [comment]
@geraki Greece 2015 was following the normal category naming pattern, so it does not need to be added to the special_exceptions.

It needs to be added to the configuration at https://commons.wikimedia.org/wiki/Module:WL_data

**Comment by JeanFred** [comment]
(Thanks for the PR though! Sorry for the short answer − in full rush of the WLM preparations ^_^')

**Comment by geraki** [comment]
> @geraki Greece 2015 was following the normal category naming pattern, so it does not need to be added to the special_exceptions.
> 
> It needs to be added to the configuration at https://commons.wikimedia.org/wiki/Module:WL_data

But isn't it looking for "Wiki Science Competition" instead of "European Science Photo Competition"?

**Comment by JeanFred** [comment]
Le mer. 28 août 2019 à 18:26, Konstantinos <notifications@github.com> a
écrit :

> @geraki <https://github.com/geraki> Greece 2015 was following the normal
> category naming pattern, so it does not need to be added to the
> special_exceptions.
>
> It needs to be added to the configuration at
> https://commons.wikimedia.org/wiki/Module:WL_data
>
> But isn't it looking for "Wiki Science Competition" instead of "European
> Science Photo Competition"?
>

No, this is taken care of by
https://github.com/JeanFred/wikiloves/blob/master/functions.py#L129-L131 :-)

**Pull request closed without merging**
